feat: only parse insecure registries if shp-output-insecure is true
Signed-off-by: Samuel Gaist <samuel.gaist@idiap.ch>

diff --git a/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml b/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
--- a/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
+++ b/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
@@ -35,6 +35,8 @@ spec:
           value: $(params.shp-source-context)
         - name: PARAM_OUTPUT_IMAGE
           value: $(params.shp-output-image)
+        - name: PARAM_OUTPUT_INSECURE
+          value: $(params.shp-output-insecure)
       command:
         - /bin/bash
       args:
@@ -43,19 +45,21 @@ spec:
           insecureRegistries=""
           inInsecureRegistries=false
 
-          while [[ $# -gt 0 ]]; do
-            arg="$1"
-            shift
+          if [[ "${PARAM_OUTPUT_INSECURE}" == "true" ]]; then
+            while [[ $# -gt 0 ]]; do
+              arg="$1"
+              shift
 
-            if [ "${arg}" == "--insecure-registries" ]; then
-              inInsecureRegistries=true
-            elif [ "${inInsecureRegistries}" == "true" ]; then
-              insecureRegistries="${insecureRegistries}${arg},"
-            else
-              echo "Invalid usage"
-              exit 1
-            fi
-          done
+              if [ "${arg}" == "--insecure-registries" ]; then
+                inInsecureRegistries=true
+              elif [ "${inInsecureRegistries}" == "true" ]; then
+                insecureRegistries="${insecureRegistries}${arg},"
+              else
+                echo "Invalid usage"
+                exit 1
+              fi
+            done
+          fi
 
           if [[ ! -z "$insecureRegistries" ]]; then
             echo "> Using insecure registries: $insecureRegistries"
