refactor: fail fast when insecure output is disabled but image points to a known insecure registry
Signed-off-by: Samuel Gaist <samuel.gaist@idiap.ch>

diff --git a/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml b/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
--- a/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
+++ b/samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
@@ -46,13 +46,15 @@ spec:
 
           insecureRegistries=""
           inInsecureRegistries=false
-          shouldExport=true
 
           function validate_insecure_output() {
             if [[ ${PARAM_OUTPUT_IMAGE} =~ $1 ]]; then
               if [[ "${PARAM_OUTPUT_INSECURE}" != "true" ]]; then
-                echo "> WARNING: insecure output registry $1 listed while insecure output is disabled, disabling export"
-                shouldExport=false
+                msg="> ERROR: insecure output registry $1 listed while insecure output is disabled"
+                echo -e $msg
+                echo -n "InsecureConfigurationError" > '$(results.shp-error-reason.path)'
+                echo -n $msg > '$(results.shp-error-message.path)'
+                exit 1
               else
                 echo "> WARNING: registry '$1' is listed in parameter 'insecure-registries' and is also declared insecure as the output of the BuildRun. The duplicate insecure declaration is unnecessary."
               fi
@@ -143,15 +145,11 @@ spec:
           exporter_args=( -layers="$LAYERS_DIR" -report=/tmp/report.toml -cache-dir="$CACHE_DIR" -app="${PARAM_SOURCE_CONTEXT}")
           grep -q "buildpack-default-process-type" "$LAYERS_DIR/config/metadata.toml" || exporter_args+=( -process-type web )
 
-          if [[ "$shouldExport" == true ]]; then
-            announce_phase "EXPORTING"
-            /cnb/lifecycle/exporter "${exporter_args[@]}" "${PARAM_OUTPUT_IMAGE}"
+          announce_phase "EXPORTING"
+          /cnb/lifecycle/exporter "${exporter_args[@]}" "${PARAM_OUTPUT_IMAGE}"
 
-            # Store the image digest
-            grep digest /tmp/report.toml | tail -n 1 | tr -d ' \"\n' | sed s/digest=// > "$(results.shp-image-digest.path)"
-          else
-            exit 1
-          fi
+          # Store the image digest
+          grep digest /tmp/report.toml | tail -n 1 | tr -d ' \"\n' | sed s/digest=// > "$(results.shp-image-digest.path)"
         - --
         - --insecure-registries
         - $(params.insecure-registries[*])
