Use array parameters, support build-args

diff --git a/samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml b/samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
--- a/samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
+++ b/samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
@@ -17,49 +17,158 @@ spec:
         - |
           set -euo pipefail
 
-          echo "Creating registries config file..."
+          # Parse parameters
+          context=
+          dockerfile=
+          image=
+          buildArgs=()
+          inBuildArgs=false
+          registriesBlock=""
+          inRegistriesBlock=false
+          registriesInsecure=""
+          inRegistriesInsecure=false
+          registriesSearch=""
+          inRegistriesSearch=false
+          tlsVerify=true
+          while [[ $# -gt 0 ]]; do
+            arg="$1"
+            shift
 
-          format(){
-              array=(`echo $1 | tr ',' ' '`)
-              str=""
-              for m in "${array[@]}"; do
-                  str=$str"'${m}', "
-              done
+            if [ "${arg}" == "--context" ]; then
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+              context="$1"
+              shift
+            elif [ "${arg}" == "--dockerfile" ]; then
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+              dockerfile="$1"
+              shift
+            elif [ "${arg}" == "--image" ]; then
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+              image="$1"
+              shift
+            elif [ "${arg}" == "--build-args" ]; then
+              inBuildArgs=true
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+            elif [ "${arg}" == "--registries-block" ]; then
+              inRegistriesBlock=true
+              inBuildArgs=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+            elif [ "${arg}" == "--registries-insecure" ]; then
+              inRegistriesInsecure=true
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesSearch=false
+            elif [ "${arg}" == "--registries-search" ]; then
+              inRegistriesSearch=true
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+            elif [ "${inBuildArgs}" == "true" ]; then
+              buildArgs+=("--build-arg" "${arg}")
+            elif [ "${inRegistriesBlock}" == "true" ]; then
+              registriesBlock="${registriesBlock}'${arg}', "
+            elif [ "${inRegistriesInsecure}" == "true" ]; then
+              registriesInsecure="${registriesInsecure}'${arg}', "
 
-              echo ${str%??}
-          }
+              # This assumes that the image is passed before the insecure registries which is fair in this context
+              if [[ ${image} == ${arg}/* ]]; then
+                tlsVerify=false
+              fi
+            elif [ "${inRegistriesSearch}" == "true" ]; then
+              registriesSearch="${registriesSearch}'${arg}', "
+            else
+              echo "Invalid usage"
+              exit 1
+            fi
+          done
 
-          cat <<EOF >/tmp/registries.conf
+          # Verify the existence of the context directory
+          if [ ! -d "${context}" ]; then
+            echo -e "The context directory '${context}' does not exist."
+            echo -n "ContextDirNotFound" > '$(results.shp-error-reason.path)'
+            echo -n "The context directory '${context}' does not exist." > '$(results.shp-error-message.path)'
+            exit 1
+          fi
+          cd "${context}"
+
+          # Verify the existence of the Dockerfile
+          if [ ! -f "${dockerfile}" ]; then
+            echo -e "The Dockerfile '${dockerfile}' does not exist."
+            echo -n "DockerfileNotFound" > '$(results.shp-error-reason.path)'
+            echo -n "The Dockerfile '${dockerfile}' does not exist." > '$(results.shp-error-message.path)'
+            exit 1
+          fi
+
+          echo "[INFO] Creating registries config file..."
+          if [ "${registriesSearch}" != "" ]; then
+            cat <<EOF >>/tmp/registries.conf
           [registries.search]
-          registries = [$(format "$(params.registry-search)")]
-
-          [registries.insecure]
-          registries = [$(format "$(params.registry-insecure)")]
-
-          [registries.block]
-          registries = [$(format "$(params.registry-block)")]
+          registries = [${registriesSearch::-2}]
 
           EOF
+          fi
+          if [ "${registriesInsecure}" != "" ]; then
+            cat <<EOF >>/tmp/registries.conf
+          [registries.insecure]
+          registries = [${registriesInsecure::-2}]
+
+          EOF
+          fi
+          if [ "${registriesBlock}" != "" ]; then
+            cat <<EOF >>/tmp/registries.conf
+          [registries.block]
+          registries = [${registriesBlock::-2}]
+
+          EOF
+          fi
 
           # Building the image
-          echo '[INFO] Building image $(params.shp-output-image)'
-          buildah bud \
-            --registries-conf='/tmp/registries.conf' \
-            --tag='$(params.shp-output-image)' \
-            --file='$(build.dockerfile)' \
-            '$(params.shp-source-context)'
+          echo "[INFO] Building image ${image}"
+          buildah bud "${buildArgs[@]}" \
+            --registries-conf=/tmp/registries.conf \
+            --tag="${image}" \
+            --file="${dockerfile}" \
+            .
 
           # Push the image
-          echo '[INFO] Pushing image $(params.shp-output-image)'
+          echo "[INFO] Pushing image ${image}"
           buildah push \
-            --tls-verify=false \
-            '$(params.shp-output-image)' \
-            'docker://$(params.shp-output-image)'
-          
+            --tls-verify="${tlsVerify}" \
+            "${image}" \
+            "docker://${image}"
+
           # Store the digest result
           buildah images \
             --format='{{.Digest}}' \
-            '$(params.shp-output-image)' | tr -d "\n" > '$(results.shp-image-digest.path)'
+            "${image}" | tr -d "\n" > '$(results.shp-image-digest.path)'
+        # That's the separator between the shell script and its args
+        - --
+        - --context
+        - $(params.shp-source-context)
+        - --dockerfile
+        - $(build.dockerfile)
+        - --image
+        - $(params.shp-output-image)
+        - --build-args
+        - $(params.build-args[*])
+        - --registries-block
+        - $(params.registries-block[*])
+        - --registries-insecure
+        - $(params.registries-insecure[*])
+        - --registries-search
+        - $(params.registries-search[*])
       resources:
         limits:
           cpu: "1"
@@ -68,12 +177,21 @@ spec:
           cpu: 250m
           memory: 65Mi
   parameters:
-    - description: The registries for searching short name images such as `golang:latest`, separated by commas.
-      name: registry-search
-      default: docker.io,quay.io
-    - description: The fully-qualified name of insecure registries. An insecure registry is one that does not have a valid SSL certificate or only does HTTP.
-      name: registry-insecure
-      default: ""
-    - description: The registries that need to block pull access.
-      name: registry-block
-      default: ""
+    - name: build-args
+      description: "The values for the args in the Dockerfile. Values must be in the format KEY=VALUE."
+      type: array
+      defaults: []
+    - name: registries-block
+      description: The registries that need to block pull access.
+      type: array
+      defaults: []
+    - name: registries-insecure
+      description: The fully-qualified name of insecure registries. An insecure registry is one that does not have a valid SSL certificate or only supports HTTP.
+      type: array
+      defaults: []
+    - name: registries-search
+      description: The registries for searching short name images such as `golang:latest`.
+      type: array
+      defaults:
+        - docker.io
+        - quay.io
