Shipwright-managed push: Sample build strategy updates

diff --git a/samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml b/samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
--- a/samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
+++ b/samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
@@ -2,27 +2,12 @@
 apiVersion: shipwright.io/v1alpha1
 kind: ClusterBuildStrategy
 metadata:
-  name: source-to-image-redhat
+  name: buildah-strategy-managed-push
 spec:
-  volumes:
-    - name: s2i
-      emptyDir: {}
   buildSteps:
-    - name: s2i-generate
-      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8:latest
-      workingDir: $(params.shp-source-root)
-      args:
-        - build
-        - $(params.shp-source-context)
-        - $(build.builder.image)
-        - $(params.shp-output-image)
-        - --as-dockerfile=/s2i/Dockerfile
-      volumeMounts:
-        - name: s2i
-          mountPath: /s2i
-    - name: buildah
+    - name: build-and-push
       image: quay.io/containers/buildah:v1.29.1
-      workingDir: /s2i
+      workingDir: $(params.shp-source-root)
       securityContext:
         privileged: true
       command:
@@ -33,47 +18,74 @@ spec:
           set -euo pipefail
 
           # Parse parameters
+          context=
+          dockerfile=
           image=
-          target=
+          buildArgs=()
+          inBuildArgs=false
           registriesBlock=""
           inRegistriesBlock=false
           registriesInsecure=""
           inRegistriesInsecure=false
           registriesSearch=""
           inRegistriesSearch=false
+          tlsVerify=true
           while [[ $# -gt 0 ]]; do
             arg="$1"
             shift
 
-            if [ "${arg}" == "--image" ]; then
+            if [ "${arg}" == "--context" ]; then
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+              context="$1"
+              shift
+            elif [ "${arg}" == "--dockerfile" ]; then
+              inBuildArgs=false
+              inRegistriesBlock=false
+              inRegistriesInsecure=false
+              inRegistriesSearch=false
+              dockerfile="$1"
+              shift
+            elif [ "${arg}" == "--image" ]; then
+              inBuildArgs=false
               inRegistriesBlock=false
               inRegistriesInsecure=false
               inRegistriesSearch=false
               image="$1"
               shift
-            elif [ "${arg}" == "--target" ]; then
-              inBuildArgs=false
+            elif [ "${arg}" == "--build-args" ]; then
+              inBuildArgs=true
               inRegistriesBlock=false
               inRegistriesInsecure=false
               inRegistriesSearch=false
-              target="$1"
-              shift
             elif [ "${arg}" == "--registries-block" ]; then
               inRegistriesBlock=true
+              inBuildArgs=false
               inRegistriesInsecure=false
               inRegistriesSearch=false
             elif [ "${arg}" == "--registries-insecure" ]; then
               inRegistriesInsecure=true
+              inBuildArgs=false
               inRegistriesBlock=false
               inRegistriesSearch=false
             elif [ "${arg}" == "--registries-search" ]; then
               inRegistriesSearch=true
+              inBuildArgs=false
               inRegistriesBlock=false
               inRegistriesInsecure=false
+            elif [ "${inBuildArgs}" == "true" ]; then
+              buildArgs+=("--build-arg" "${arg}")
             elif [ "${inRegistriesBlock}" == "true" ]; then
               registriesBlock="${registriesBlock}'${arg}', "
             elif [ "${inRegistriesInsecure}" == "true" ]; then
               registriesInsecure="${registriesInsecure}'${arg}', "
+
+              # This assumes that the image is passed before the insecure registries which is fair in this context
+              if [[ ${image} == ${arg}/* ]]; then
+                tlsVerify=false
+              fi
             elif [ "${inRegistriesSearch}" == "true" ]; then
               registriesSearch="${registriesSearch}'${arg}', "
             else
@@ -81,6 +93,23 @@ spec:
               exit 1
             fi
           done
+
+          # Verify the existence of the context directory
+          if [ ! -d "${context}" ]; then
+            echo -e "The context directory '${context}' does not exist."
+            echo -n "ContextDirNotFound" > '$(results.shp-error-reason.path)'
+            echo -n "The context directory '${context}' does not exist." > '$(results.shp-error-message.path)'
+            exit 1
+          fi
+          cd "${context}"
+
+          # Verify the existence of the Dockerfile
+          if [ ! -f "${dockerfile}" ]; then
+            echo -e "The Dockerfile '${dockerfile}' does not exist."
+            echo -n "DockerfileNotFound" > '$(results.shp-error-reason.path)'
+            echo -n "The Dockerfile '${dockerfile}' does not exist." > '$(results.shp-error-message.path)'
+            exit 1
+          fi
 
           echo "[INFO] Creating registries config file..."
           if [ "${registriesSearch}" != "" ]; then
@@ -107,31 +136,47 @@ spec:
 
           # Building the image
           echo "[INFO] Building image ${image}"
-          buildah bud \
+          buildah bud "${buildArgs[@]}" \
             --registries-conf=/tmp/registries.conf \
-            --tag="${image}"
+            --tag="${image}" \
+            --file="${dockerfile}" \
+            .
 
-          # Write the image
-          echo "[INFO] Writing image ${image}"
+          # Push the image
+          echo "[INFO] Pushing image ${image}"
           buildah push \
+            --digestfile='$(results.shp-image-digest.path)' \
+            --tls-verify="${tlsVerify}" \
             "${image}" \
-            "oci:${target}"
+            "docker://${image}"
         # That's the separator between the shell script and its args
         - --
+        - --context
+        - $(params.shp-source-context)
+        - --dockerfile
+        - $(build.dockerfile)
         - --image
         - $(params.shp-output-image)
+        - --build-args
+        - $(params.build-args[*])
         - --registries-block
         - $(params.registries-block[*])
         - --registries-insecure
         - $(params.registries-insecure[*])
         - --registries-search
         - $(params.registries-search[*])
-        - --target
-        - $(params.shp-output-directory)
-      volumeMounts:
-        - name: s2i
-          mountPath: /s2i
+      resources:
+        limits:
+          cpu: "1"
+          memory: 2Gi
+        requests:
+          cpu: 250m
+          memory: 65Mi
   parameters:
+    - name: build-args
+      description: "The values for the args in the Dockerfile. Values must be in the format KEY=VALUE."
+      type: array
+      defaults: []
     - name: registries-block
       description: The registries that need to block pull access.
       type: array
